# Generated by Django 2.1.2 on 2018-10-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('fec_nacimiento', models.DateField()),
                ('fono', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('tipo_vivienda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
